repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: clang-format
        name: Formateando archivos C con Clang-Format local
        entry: clang-format
        language: system
        files: \.(c|h)$
        args: ["-i"]
